<!DOCTYPE html>
<html>
<head>
    <title>Barangay Blotter Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #7367f0; padding-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #7367f0; color: white; font-weight: bold; }
        .status-open { background-color: #f8d7da; color: #721c24; }
        .status-resolved { background-color: #d4edda; color: #155724; }
        .footer { margin-top: 40px; text-align: center; font-size: 0.9em; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ config('app.name') }}</h1>
        <h2>Blotter Report</h2>
        <p>Generated on {{ now()->format('F d, Y \\a\\t g:i A') }}</p>
    </div>

    <h3>Barangay Blotter Cases</h3>
    <table>
        <thead>
            <tr>
                <th>Incident Date</th>
                <th>Parties Involved</th>
                <th>Reported By</th>
                <th>Status</th>
                <th>Resolution Notes</th>
            </tr>
        </thead>
        <tbody>
            @foreach($blotters as $blotter)
            <tr>
                <td>{{ $blotter->incident_date->format('M d, Y') }}</td>
                <td>{{ $blotter->parties->pluck('name')->implode(', ') }}</td>
                <td>{{ $blotter->reportedBy->name ?? 'N/A' }}</td>
                <td><span class="badge px-3 py-2 status-{{ strtolower($blotter->status) }}">{{ $blotter->status }}</span></td>
                <td>{{ Str::limit($blotter->resolution_notes, 50) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Barangay Information System | Official Document | Total Cases: {{ $blotters->count() }}</p>
        <p>Generated by {{ Auth::user()->name ?? 'System Administrator' }}</p>
    </div>
</body>
</html>

