<!DOCTYPE html>
<html>
<head>
    <title>Barangay Document Requests Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #7367f0; padding-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #7367f0; color: white; font-weight: bold; }
        .status-upcoming { background-color: #d1ecf1; color: #0c5460; }
        .status-pending { background-color: #fff3cd; color: #856404; }
        .status-approved { background-color: #d4edda; color: #155724; }
        .status-released { background-color: #cce5ff; color: #004085; }
        .footer { margin-top: 40px; text-align: center; font-size: 0.9em; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ config('app.name') }}</h1>
        <h2>Document Requests Report</h2>
        <p>Generated on {{ now()->format('F d, Y \\a\\t g:i A') }}</p>
    </div>

    <h3>Document Request Summary</h3>
    <table>
        <thead>
            <tr>
                <th>Resident</th>
                <th>Document Type</th>
                <th>Date Requested</th>
                <th>Status</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            @foreach($requests as $request)
            <tr>
                <td>{{ $request->resident->full_name ?? 'N/A' }}</td>
                <td>{{ $request->documentType->name ?? 'N/A' }}</td>
                <td>{{ $request->created_at->format('M d, Y') }}</td>
                <td><span class="badge px-3 py-2 status-{{ strtolower($request->status) }}">{{ $request->status }}</span></td>
                <td>{{ Str::limit($request->notes, 50) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Barangay Information System | Official Document | Total Requests: {{ $requests->count() }}</p>
        <p>Generated by {{ Auth::user()->name ?? 'System Administrator' }}</p>
    </div>
</body>
</html>

