<!DOCTYPE html>
<html>
<head>
    <title>Barangay Events Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #7367f0; padding-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #7367f0; color: white; font-weight: bold; }
        .status-upcoming { background-color: #d1ecf1; color: #0c5460; }
        .status-ongoing { background-color: #fff3cd; color: #856404; }
        .status-completed { background-color: #d4edda; color: #155724; }
        .footer { margin-top: 40px; text-align: center; font-size: 0.9em; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ config('app.name') }}</h1>
        <h2>Events Report</h2>
        <p>Generated on {{ now()->format('F d, Y \\a\\t g:i A') }}</p>
    </div>

    <h3>Community Events Summary</h3>
    <table>
        <thead>
            <tr>
                <th>Event Title</th>
                <th>Date & Time</th>
                <th>Location</th>
                <th>Status</th>
                <th>Attendance</th>
                <th>Created By</th>
            </tr>
        </thead>
        <tbody>
            @foreach($events as $event)
            <tr>
                <td>{{ Str::limit($event->title, 30) }}</td>
                <td>{{ $event->event_date->format('M d, Y') }}<br><small>{{ $event->start_time }} - {{ $event->end_time }}</small></td>
                <td>{{ Str::limit($event->location, 25) }}</td>
                <td><span class="badge px-3 py-2 status-{{ strtolower($event->status) }}">{{ $event->status }}</span></td>
                <td>{{ $event->eventParticipants->count() }} participants</td>
                <td>{{ $event->createdBy->name ?? 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Barangay Information System | Official Document | Total Events: {{ $events->count() }}</p>
        <p>Generated by {{ Auth::user()->name ?? 'System Administrator' }}</p>
    </div>
</body>
</html>

