<!DOCTYPE html>
<html>
<head>
    <title>Barangay Population Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #7367f0; padding-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #7367f0; color: white; font-weight: bold; }
        .total { background-color: #f8f9fa; font-weight: bold; font-size: 1.1em; }
        .footer { margin-top: 40px; text-align: center; font-size: 0.9em; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ config('app.name') }}</h1>
        <h2>Population Report</h2>
        <p>Generated on {{ now()->format('F d, Y \\a\\t g:i A') }}</p>
    </div>

    <h3>Population by Purok</h3>
    <table>
        <thead>
            <tr>
                <th>Purok Name</th>
                <th>Total Residents</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $row)
            <tr>
                <td>{{ $row->name }}</td>
                <td>{{ number_format($row->total) }}</td>
            </tr>
            @endforeach
            <tr class="total">
                <td><strong>GRAND TOTAL</strong></td>
                <td><strong>{{ number_format($data->sum('total')) }}</strong></td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        <p>Barangay Information System | Official Document</p>
        <p>Generated by {{ Auth::user()->name ?? 'System' }}</p>
    </div>
</body>
</html>

